# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-06-28 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=250)),
                ('lName', models.CharField(max_length=250)),
                ('dob', models.DateField(max_length=250)),
                ('occupation', models.CharField(max_length=250)),
                ('signedup', models.DateField(max_length=250)),
            ],
        ),
    ]
